name: froebel
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Capriola
  #     fonts:
  #       - asset: assets/fonts/Capriola-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Capriola-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Capriola-SemiBold.ttf
  #         weight: 600
